

test_icalstr = """BEGIN:VCALENDAR
VERSION:2.0
PRODID:{publisher}
BEGIN:VEVENT
UID:123456789@example.com
LOCATION:{location}
SUMMARY:{summary}
DESCRIPTION:{description}
CLASS:{cls}
DTSTART:{start}
DTEND:{end}
DTSTAMP:{stamp}
END:VEVENT
BEGIN:VALARM
TRIGGER:-PT15M
DESCRIPTION:Booking
ACTION:DISPLAY
END:VALARM
END:VCALENDAR"""
